version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "adenElectronico"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1lpkm1wayiegy"
s3_prefix = "adenElectronico"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
