AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  adenApp

  SAM Template for adonApp for expedite maintenance reporting
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  CallsLogs:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: ContactId
          AttributeType: S
        - AttributeName: folio
          AttributeType: S
      KeySchema: 
        - AttributeName: ContactId
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
      - IndexName: folio-call
        KeySchema:
        - AttributeName: folio
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
  EscalationMatrix:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: NumeroDestino
          AttributeType: S
      KeySchema: 
        - AttributeName: NumeroDestino
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: makeCall.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBReadPolicy:
            TableName: !Ref CallsLogs
        - Statement:
          - Sid: MakeConnectCall
            Effect: Allow
            Action:
            - connect:StartOutboundVoiceContact
            Resource: '*'
      Architectures:
        - arm64
      MemorySize: 160
      Environment:
        Variables:
          tableName : !Ref CallsLogs
  EscalationCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: makeEscalationCall.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref CallsLogs
        - Statement:
          - Sid: MakeConnectCall
            Effect: Allow
            Action:
            - connect:StartOutboundVoiceContact
            Resource: '*'
        
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
  LogCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: callLogger.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy :
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
  AckCallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: callAcker.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy :
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
  IsCallAckedFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: callAcked.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBReadPolicy :
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
  ConnectLambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn: AckCallFunction
    Properties:
      FunctionName: !Ref AckCallFunction
      Action: 'lambda:InvokeFunction'
      Principal: 'connect.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: arn:aws:connect:us-east-1:668984504585:instance/40f62289-8adf-4f1a-b934-328736bd08de
    # Folio Lambda Functions
  LogFolioFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: folioLogger.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy :
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
          
  GetFolioDeatailAPIGW:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName : Prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'X-Forwarded-For,Content-Type'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
  GetFolioFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: folioGet.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBReadPolicy:
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
          indexName : 'folio-call'
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /getFolioDetails
            Method: get
            RestApiId:
              Ref: GetFolioDeatailAPIGW
  CloseFolioFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: folioClose.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref CallsLogs
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
          indexName : 'folio-call'
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /closeFolioDetails
            Method: post
            RestApiId:
              Ref: GetFolioDeatailAPIGW
              
  NotificarLlegadaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: folioNotifica.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBWritePolicy:
            TableName: !Ref CallsLogs
        - Statement:
          - Sid: StartExecutionPolicy
            Effect: Allow
            Action:
            - states:StartExecution
            Resource: '*'
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          tableName : !Ref CallsLogs
          escalationMachine : "arn:aws:states:us-east-1:668984504585:stateMachine:makeEscalation"
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /notitificaLlegada
            Method: get
            RestApiId:
              Ref: GetFolioDeatailAPIGW
  checkEscalateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: checkEscalate.handler
      Runtime: python3.8
      Policies: 
        - AWSLambdaExecute
        - DynamoDBReadPolicy :
            TableName: !Ref CallsLogs
        - DynamoDBReadPolicy :
            TableName: !Ref EscalationMatrix
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          callTableName : !Ref CallsLogs
          escalationTableName : !Ref EscalationMatrix